### ISSUE TITLE
AttributeError: speed is not an attribute of gripper_serviceRequest

### ISSUE THREAD

**Issue by damounayman** [macs-lab/robotiq_hande_ros_driver#2]
Hi,

I'am working with UR3e-series robot with hande gripper and ROS. I'm triying to control the gripper with hande_ros_driver. When i use the test script I get the following error (**speed is not an attribute of gripper_serviceRequest**): 
```sh
`[INFO] [1619019244.899597]: using service
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    response = gripper_srv(position=0, speed=255, force=255)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 498, in call
    request = rospy.msg.args_kwds_to_message(self.request_class, args, kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 105, in args_kwds_to_message
    return data_class(**kwds)
  File "/home/geekayman/ur_real_robot_ws/devel/lib/python2.7/dist-packages/robotiq_hande_ros_driver/srv/_gripper_service.py", line 35, in __init__
    super(gripper_serviceRequest, self).__init__(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 351, in __init__
    raise AttributeError('%s is not an attribute of %s' % (k, self.__class__.__name__))
AttributeError: speed is not an attribute of gripper_serviceRequest`
```
when I use the old version it works but I can only open and close. I can't get an intermediate position of the gripper.

```python
rospy.init_node("gripper_test_node")
## using ROS service
rospy.loginfo("using service")
gripper_srv = rospy.ServiceProxy('gripper_service', gripper_service)
# open gripper
response = gripper_srv(1)
# close gripper
response = gripper_srv(0)
```
**Versions**
- ROS Driver version: ROS Melodic
-  Affected Robot Hardware Version(s): UR3e-series

**Comment by xiaohuits** [comment]
Thanks for reporting this error. The new service definition was not pushed somehow. This error should have been resolved in  eee1c17afc6a7d7f2a4b9714fe22d40dfb789ecc.
